export const GET_EDUCATION = 'GET_EDUCATION'

export const GET_LOCATION = 'GET_LOCATION'
export const SET_LOCATION = 'SET_LOCATION'

export const GET_USERINFO = 'GET_USERINFO'
export const CREATE_USERINFO = 'CREATE_USERINFO'
export const SET_USERINFO = 'SET_USERINFO'
export const UPLOAD_USERINFO = 'UPLOAD_USERINFO'


export const GET_AGE = 'GET_AGE'

export const GET_SALARY = 'GET_SALARY'

export const GET_BUDGETFORCOURSE = 'GET_BUDGETFORCOURSE'

export const GET_IDENTITY = 'GET_IDENTITY'

export const GET_JOBFUNCTIONS = 'GET_JOBFUNCTIONS'

export const GET_YEAREXPERIENCE = 'GET_YEAREXPERIENCE'


